array = ['Paul Han',
'Inga Nikitina',
'Brian Choy',
'Andrei Motinga',
'Mubiyna Casey',
'Geraldina Alvarez Garcia',
'Stephanie Aviles',
'Lewaa Bahmad',
'Maria Antropova',
'Jayana Johnson',
'Keith Embler',
'Ming Zhang',
'Tiffany Haltom',
'Jordan Falcon',
'Sanjay Chakravorty',
'Anton Halim',
'Hessvacio Hassan',
'Mykle Nero',
'Earl Clifton',
'Shawn Hansen',
'Danielle Hill',
'Sebastian King',
'Andrew Cabrera',
'Daniel Ferrer',
'Lindsay Padian',
'Lezou Dali',
'Eric Orellana',
'Ashley Chu',
'david lorente',
'Daniel Aksenov',
'Leah Suter',
'In Ho Hwang']
8.times do |i|
  puts i
  puts i*4
  #puts array.slice(i,i*4)
end